#!/usr/bin/bash

ABSPATHBOT="/usr/src/bot"
MYBOTPRESEN="$ABSPATHBOT/src/botpresent"
IPADDR='8.8.8.8' # Google's public DNS server

function runthebot(){
    cd $ABSPATHBOT && python $MYBOTPRESEN start
}
[[ -z `ping -c1 $IPADDR |& grep -o 'Network is unreachable'` ]] || echo "Network is unreachable"
[[ -z `ping -c3 $IPADDR |& grep -o '100% packet loss'` ]] && runthebot || echo "packet loss"

